### ISSUE TITLE
Old link to GPO policies

### ISSUE THREAD

**Issue by modir** [thundernest/enterprise-docs#3]
The link to the policy templates is pointing to https://github.com/thundernest/policy-templates which is a fork of https://github.com/mozilla/policy-templates.

The fork has his last commit 2 years ago. The main repo had the last commit 2 days ago. I would recommend to point to the main repo again.

**Comment by jobisoft** [comment]
We updated our policies. Where did you find the link which still uses `thundernest` ? We should replace it with the correct one:

https://github.com/thunderbird/policy-templates

**Comment by modir** [comment]
The last link here: https://github.com/thunderbird/enterprise-docs/blob/master/manage-updates-policies-and-customization/managing-thunderbird-updates.md
and the last link here: https://github.com/thunderbird/enterprise-docs/blob/master/manage-updates-policies-and-customization/managing-thunderbird-policies/customizing-thunderbird-using-policies.json.md

**Comment by jobisoft** [comment]
Filed https://github.com/thunderbird/enterprise-docs/pull/7
